build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 30

naming:
  active: true
  ClassNaming:
    active: true
  FunctionNaming:
    active: true
  VariableNaming:
    active: true

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
  WildcardImport:
    active: true
